version: "3.9"

services:
  db-app:
    image: 'mysql:${MYSQL_VERSION}'
    volumes:
      - db_vol_app:/var/lib/mysql2
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    env_file:
      - .env
    networks:
      - wp
    
  wordpress:
    depends_on:
      - db-app
    image: 'wordpress:${WORDPRESS_VERSION}'
    # build: . # Building and use image from Dockerfile
    restart: always
    ports:
      - "8000:80"
      - "443:443"
    restart: always
    volumes:
      - ./wp-content:/var/www/html/wp-content
    env_file:
      - .env
    networks:
      - wp

  phpmyadmin:
    depends_on: 
      - db-app
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8001:80
    env_file:
      - .env
    networks:
      - wp
  
volumes:
  db_vol_app: {}
networks:
  wp: